"""empty message

Revision ID: 51ec692c39ca
Revises: b0c0f2528a49
Create Date: 2023-01-14 11:56:23.500152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51ec692c39ca'
down_revision = 'b0c0f2528a49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twilio_sid', sa.String(length=50), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('identity', sa.String(length=50), nullable=True),
    sa.Column('proxy_address', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DELETED', name='status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('twilio_sid', 'deleted_at', name='unique__twilio_sid__deleted_at')
    )
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('twilio_sid', sa.String(length=50), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('media', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DELETED', name='status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['conversation_participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('twilio_sid', 'deleted_at', name='unique__twilio_sid__deleted_at')
    )

    op.execute('INSERT INTO conversation_participants SELECT * FROM participants')
    op.execute('INSERT INTO conversation_messages SELECT id, conversation_id, participant_id, twilio_sid, body, media, status, created_at, modified_at, deleted_at FROM messages')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('unique__twilio_sid__deleted_at')
    op.drop_table('messages')

    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index('unique__twilio_sid__deleted_at')
    op.drop_table('participants')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('twilio_sid', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('conversation_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('identity', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('proxy_address', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('status', mysql.ENUM('ACTIVE', 'INACTIVE', 'DELETED'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('modified_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name='participants_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index('unique__twilio_sid__deleted_at', ['twilio_sid', 'deleted_at'], unique=False)

    op.create_table('messages',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('participant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('twilio_sid', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('body', mysql.TEXT(), nullable=False),
    sa.Column('media', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.ENUM('ACTIVE', 'INACTIVE', 'DELETED'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('modified_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=False),
    sa.Column('conversation_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name='messages_ibfk_2'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], name='messages_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('unique__twilio_sid__deleted_at', ['twilio_sid', 'deleted_at'], unique=False)

    op.drop_table('conversation_messages')
    op.drop_table('conversation_participants')
    # ### end Alembic commands ###
