"""empty message

Revision ID: 8ab02d1698d4
Revises: 9c3269c41bc9
Create Date: 2023-01-19 11:15:59.885417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab02d1698d4'
down_revision = '9c3269c41bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('us_cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('city_ascii', sa.String(length=50), nullable=False),
    sa.Column('state_id', sa.String(length=50), nullable=False),
    sa.Column('state_name', sa.String(length=50), nullable=False),
    sa.Column('county_fips', sa.String(length=50), nullable=False),
    sa.Column('county_name', sa.String(length=50), nullable=False),
    sa.Column('lat', sa.String(length=50), nullable=False),
    sa.Column('lng', sa.String(length=50), nullable=False),
    sa.Column('population', sa.String(length=50), nullable=False),
    sa.Column('density', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('military', sa.String(length=50), nullable=False),
    sa.Column('incorporated', sa.String(length=50), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('ranking', sa.String(length=50), nullable=False),
    sa.Column('zips', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Import US cities from sql file
    with open('migrations/db-dumps/us_cities.sql', "r") as f:
        content = f.read()
        for row in content.split(';'):
            if row:
                op.execute(row)
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_call_sid', sa.String(length=50), nullable=True))

    with op.batch_alter_table('subaccounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ivr_flow_sid', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subaccounts', schema=None) as batch_op:
        batch_op.drop_column('ivr_flow_sid')
        
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.drop_column('source_call_sid')

    op.drop_table('us_cities')
    # ### end Alembic commands ###
