"""empty message

Revision ID: 934e432b0f42
Revises: c656c7851928
Create Date: 2023-01-27 13:05:41.885251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934e432b0f42'
down_revision = 'c656c7851928'
branch_labels = None
depends_on = None


def upgrade():
    op.execute('update contacts set sms_consent=true where sms_consent is null')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('delivery_receipts', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_messages', schema=None) as batch_op:
        batch_op.drop_column('delivery_receipts')
        batch_op.drop_column('delivery')

    # ### end Alembic commands ###
