"""empty message

Revision ID: 94212122dba2
Revises: c09d3c40ca1e
Create Date: 2022-12-28 07:50:18.623268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94212122dba2'
down_revision = 'c09d3c40ca1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subaccounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('call_logs_sync_service_sid', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subaccounts', schema=None) as batch_op:
        batch_op.drop_column('call_logs_sync_service_sid')

    # ### end Alembic commands ###
