"""empty message

Revision ID: a65774c03dc7
Revises: 51ec692c39ca
Create Date: 2023-01-16 11:43:52.333349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a65774c03dc7'
down_revision = '51ec692c39ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subaccounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_service_sid', sa.String(length=50), nullable=True))
        batch_op.drop_column('chat_service_sid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subaccounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_service_sid', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('conversation_service_sid')

    # ### end Alembic commands ###
