"""empty message

Revision ID: aeaca18210d5
Revises: 
Create Date: 2022-12-16 18:46:52.169868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeaca18210d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subaccounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('subtenant_id', sa.String(length=100), nullable=False),
    sa.Column('account_sid', sa.String(length=50), nullable=False),
    sa.Column('auth_token', sa.String(length=50), nullable=False),
    sa.Column('account_status', sa.String(length=20), nullable=False),
    sa.Column('api_key', sa.String(length=50), nullable=True),
    sa.Column('api_secret', sa.String(length=50), nullable=True),
    sa.Column('twiml_app_sid', sa.String(length=50), nullable=True),
    sa.Column('sync_service_sid', sa.String(length=50), nullable=True),
    sa.Column('chat_service_sid', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_sid', 'deleted_at', name='unique__account_sid__deleted_at'),
    sa.UniqueConstraint('tenant_id', 'subtenant_id', 'deleted_at', name='unique__tenant_id_subtenant_id__deleted_at')
    )
    op.create_table('emergency_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subaccount_id', sa.Integer(), nullable=False),
    sa.Column('twilio_sid', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=50), nullable=False),
    sa.Column('street', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('postal_code', sa.String(length=50), nullable=False),
    sa.Column('iso_country', sa.String(length=10), nullable=False),
    sa.Column('emergency_enabled', sa.Boolean(), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subaccount_id'], ['subaccounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('twilio_sid', 'deleted_at', name='unique__twilio_sid__deleted_at')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emergency_addresses')
    op.drop_table('subaccounts')
    # ### end Alembic commands ###
