"""empty message

Revision ID: b05f04e904ce
Revises: ef9f71a00dc6
Create Date: 2022-12-29 18:57:08.557222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05f04e904ce'
down_revision = 'ef9f71a00dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_forwarding_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('number_type', sa.Enum('SELF', 'INTERNAL', 'EXTERNAL', name='phonenumbertypes'), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phone_numbers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number_id', 'number', 'deleted_at', name='unique__phone_number_id__number__deleted_at')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call_forwarding_rules')
    # ### end Alembic commands ###
