"""empty message

Revision ID: c58a92b8e032
Revises: 8ab02d1698d4
Create Date: 2023-01-19 20:00:16.634591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c58a92b8e032'
down_revision = '8ab02d1698d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voicemails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DELETED', name='status'), nullable=False))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('recording_start_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('recording_status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('s3_path',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('pushed_to_s3')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voicemails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pushed_to_s3', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.alter_column('s3_path',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('recording_status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('recording_start_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
