"""empty message

Revision ID: d98593195234
Revises: c58a92b8e032
Create Date: 2023-01-19 22:16:05.173887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd98593195234'
down_revision = 'c58a92b8e032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voicemails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'phone_numbers', ['phone_number_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voicemails', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('phone_number_id')

    # ### end Alembic commands ###
